spring.application.name=order-service-java
server.port=8082

# src/main/resources/application.properties
# URL do ERP Adapter (local)
#erp.adapter.url=http://localhost:8081/erp-sap

# src/main/resources/application-docker.properties
# URL do ERP Adapter (Docker Compose)
erp.adapter.url=http://erp-sap:8080
