spring.application.name=erp-adapter-java
server.port=8081

# src/main/resources/application.properties
# Exemplo: URL futura do Payment Service local
#payment.service.url=http://localhost:8083/payments

# src/main/resources/application-docker.properties
# Exemplo: URL futura do Payment Service Docker
payment.service.url=http://payment-service:8080/payments