spring.application.name=bff-java
server.port=8080

# src/main/resources/application.properties
# URL do order-service (local)
#order.service.url=http://localhost:8082/orders

# src/main/resources/application-docker.properties
# URL do order-service (Docker Compose)
order.service.url=http://order-service:8080/orders